### ISSUE TITLE
1

### ISSUE THREAD

**Issue by TunSawThant** [friendlybigyan/CUI-Calculator#1]
5 * (1+ (3*78 -22)
this can not show error ..... .This is expression is  need " )" at the last sentence.

**Comment by friendlybigyan** [comment]
Working on that autocompletion part still. Thanks though, will look into it.

**Comment by TunSawThant** [comment]
> Working on that autocompletion part still. Thanks though, will look into it.
> Edit: It's fixed now!
wow..
![python_img](https://user-images.githubusercontent.com/50229688/99228439-02bb7600-281b-11eb-9763-1bbd9f6d2a7c.JPG)
how to you think this equation => 4/(6+4-10) .
This must be infinity that i think.

**Comment by friendlybigyan** [comment]
> > Working on that autocompletion part still. Thanks though, will look into it.
> > Edit: It's fixed now!
> > wow..
> > ![python_img](https://user-images.githubusercontent.com/50229688/99228439-02bb7600-281b-11eb-9763-1bbd9f6d2a7c.JPG)
> > how to you think this equation => 4/(6+4-10) .
> > This must be infinity that i think.

You are absolutely right. I had been focusing in the other parts so much that the main calculations have been neglected. I'll have them working right away.

**Comment by friendlybigyan** [comment]
> > Working on that autocompletion part still. Thanks though, will look into it.
> > Edit: It's fixed now!
> > wow..
> > ![python_img](https://user-images.githubusercontent.com/50229688/99228439-02bb7600-281b-11eb-9763-1bbd9f6d2a7c.JPG)
> > how to you think this equation => 4/(6+4-10) .
> > This must be infinity that i think.

My man, it does work. At least in the latest commits.
![Screenshot_20210101_072058](https://user-images.githubusercontent.com/47275884/103432107-600c5a80-4c02-11eb-8fdf-ead9c709196e.png)
